package thaumicenergistics.init;

/**
 * @author BrockWS
 */
public enum ModGUIs {
    ESSENTIA_IMPORT_BUS,
    ESSENTIA_EXPORT_BUS,
    ESSENTIA_STORAGE_BUS,
    ESSENTIA_TERMINAL,
    ARCANE_TERMINAL,
    ARCANE_INSCRIBER,

    AE2_CRAFT_AMOUNT,
    AE2_CRAFT_CONFIRM,
    AE2_CRAFT_STATUS,

    KNOWLEDGE_CORE_ADD,
    KNOWLEDGE_CORE_DEL,
    KNOWLEDGE_CORE_VIEW
}
